# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-18 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publishing_data',
            new_name='publishing_date',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Keywords'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
    ]
