# Generated by Django 3.0.5 on 2020-04-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20200419_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bertanswer',
            field=models.TextField(default='-', verbose_name='Bert Answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='bertconf',
            field=models.TextField(default=0, verbose_name='Confidence'),
            preserve_default=False,
        ),
    ]
